### ISSUE TITLE
Can't find the crystal model

### ISSUE THREAD

**Issue by sketchpunk** [oculus-samples/Unity-FirstHand#1]
The crystal that goes into the palm of the hands, I'm unable to find the model for it in the project. Can someone direct me to where it is or what its called?

**Comment by kpfeifer-meta** [comment]
It looks like those are missing from the open source project.  Let me look into getting them added :)

**Comment by kpfeifer-meta** [comment]
Okay @sketchpunk added the models and materials for those crystals.  Let me know if you have any issues!
