### ISSUE TITLE
How to attach the Glove with hands?

### ISSUE THREAD

**Issue by floodsung** [oculus-samples/Unity-FirstHand#2]
Hi,
This project is awesome! 
I wish to wear the Glove and fire like the full app does, however the open source project does not provide this.

Will you open source it? or  do you have any suggestions to do that?
Thx.

**Comment by tdaviesfb** [comment]
Hi floodsung,
At this point we don't have near term plans to enable wearing of the gloves, as in the full app. However, you are able to enable the blaster and shield poses using buttons to the right of your view when in the app. You should then be able to make the poses with your regular hands and the blast/shield functionality should work. Please let me know if you have any other questions!
