### ISSUE TITLE
Cannot move player object away from 0,0,0

### ISSUE THREAD

**Issue by ibytergj** [oculus-samples/Unity-FirstHand#3]
This demo also suffers from the same issue I reported as a bug here -https://oculusdevelopers.zendesk.com/hc/en-us/requests/39022
Player object must stay at 0,0,0 or hands get offset incorrectly
You can see this by setting the player object to .2, 0,-2 for example.
I have had my support ticket open since June 23, 2022 17:01 with no further updates since initial contact

**Comment by dnelson-meta** [comment]
Hi @ibytergj, thank you for reporting this. This is an issue with the version of Interaction SDK used in the First Hand demo, and has since been resolved. The fix will be available in an upcoming Interaction SDK release.

**Comment by ibytergj** [comment]
Hello, I just downloaded release 43 from the Unity asset store and the fix is not in that version. Will you be able to tell me when we can expect the fix to ship?

**Comment by kpfeifer-meta** [comment]
@ibytergj Were you able to try with v44?  I think that is where this change was added.   Please let me know if this is still an issue, thanks!

**Comment by ibytergj** [comment]
Hi I did try this and it appears to be fixed. Thank you so much for
following up. The issue can be closed.
