### ISSUE TITLE
two hands demo

### ISSUE THREAD

**Issue by zlggithubzlg** [oculus-samples/Unity-FirstHand#6]
two hands demo

**Comment by dyaro-meta** [comment]
Could you elaborate on what you want to see here?

**Comment by zlggithubzlg** [comment]
I want to take the knife out of its sheath, and when it is drawn out, follow the shape of the sheath, and when it is fully drawn out, the knife can be waved freely. When I draw the knife, I should follow a certain path, and only after I pull it out can I wave it by myself. What should I do?
