### ISSUE TITLE
How to use it with other devices

### ISSUE THREAD

**Issue by juan-xin-cai** [oculus-samples/Unity-FirstHand#7]
I want to use this SDK on other devices and what configuration needs to be done？

**Comment by kpfeifer-meta** [comment]
Hi @guoliang1996!  ISDK can indeed be used on other devices, but at this time we don't have a process written up to describe the method as it has only been done experimentally and we haven't had time to generalize the process for any given hardware out there.

**Comment by Gyliiiiii** [comment]
May I ask when the detailed process description can be formed? We really hope that our equipment can be connected to ISDK, because ISDK is so easy to use！！

**Comment by juan-xin-cai** [comment]
May I ask when the detailed process description can be formed? We really hope that our equipment can be connected to ISDK, because ISDK is really great!!

**Comment by Gyliiiiii** [comment]
May I ask when the detailed process description can be formed? We really hope that our equipment can be connected to ISDK, because ISDK is really great!!

**Comment by juan-xin-cai** [comment]
@kpfeifer-meta

**Comment by kpfeifer-meta** [comment]
Glad you're liking ISDK!!  We currently don't have a timeline to document the process with other hardware.  That said, I'm hoping one of the team (possibly me) will get time to put something together in the next couple of months.

**Comment by juan-xin-cai** [comment]
I`m Looking forward to it
