### ISSUE TITLE
How do you run this via Quest Link?

### ISSUE THREAD

**Issue by fmatulic** [oculus-samples/Unity-FirstHand#9]
Can you provide information on how to run this from Unity so that it plays on the headset via Quest Link? I've followed general instructions I've found on the net, but when I hit play the application doesn't show in the Quest.

**Comment by RickAtMeta** [comment]
Hello, sorry you are having issues running link. This isn't really an oculus samples specific issue but I've looked up a few other threads discussing this. Keep in mind your specific version of Unity, Oculus app version and platform (PC or Mac) will all affect your setup. Also, at this time, Link is not supported over Mac.

Some thread discussing this:
https://forum.unity.com/threads/getting-quest-link-to-work-in-unity.780203/
https://forum.unity.com/threads/oculus-link-not-working-in-play-mode.1067882/
https://forum.unity.com/threads/how-to-play-vr-game-in-unity-editor-with-oculus-quest-2-via-oculus-link.1277360/

I'm going to close this issue on this forum. Please try the general Unity and Oculus forums for this type of support. They should be much better equipped to help resolve your issue.
